### ISSUE TITLE
Implement manualMowing

### ISSUE THREAD

**Issue by afuerhoff** [jonkristian/alko#18]
Mostly the same as mowing window issue#8

My rest command:

rest_command:
  alko_manualmowing_set:
    url: !secret alko_url_state_desired
    method: PATCH
    headers:
      Authorization: !secret alko_bearer
      Accept: application/json
    verify_ssl: true
    payload: |
      { "manualMowing": { "activityMode": {{ act }},"marginMode": {{ mar }},"narrowPassageMode": {{ pas }},"startHour": {{ hour }},"startMinute": {{ minute }},"duration": {{ duration }}, "entryPoint": {{ ep }} }}

state/reported:

"manualMowing": {
	"activityMode": false,
	"marginMode": false,
	"narrowPassageMode": false,
	"startHour": 0,
	"startMinute": 0,
	"duration": 0,
	"entryPoint": 34
},

Entry point 34 -> do nothing

**Comment by DIYtechie** [comment]
This looks interesting and like a good implementation, but I'm not sure I understand fully (I don't understand the German language) and I'm not sure about indentation in the implementation example above etc.

Is it possible to manually start mowing from a certain entrypoint using the API? I mean without creating a schedule but just starting _immediately_ (and not in 5 minutes and every week)?

**Comment by DIYtechie** [comment]
> It's possible. This is what you see in the pictures. You can choose the entry point, the type of mowing (with border, passage or only mowing) and the duration. The start time could be set to current or any time. In an automation you can set this fields to fixed values and press the a button.

Amazing! Thanks! Having a button for my front yard and a button for my back yard is exactly what I hope to achieve.

**What I think I understand is this:** 

I need to add this to my configuration.yaml:

```
rest_command:
  alko_manualmowing_set:
    url: !secret alko_url_state_desired
    method: PATCH
    headers:
      Authorization: !secret alko_bearer
      Accept: application/json
    verify_ssl: true
    payload: >
      {
        "manualMowing": {
          "activityMode": {{ act }},
          "marginMode": {{ mar }},
          "narrowPassageMode": {{ pas }},
          "startHour": {{ hour }},
          "startMinute": {{ minute }},
          "duration": {{ duration }},
          "entryPoint": {{ ep }}
        }
      }

```

and 

I need to add the following to my secrets.yaml:

```
alko_url_state_desired: >
  https://api.al-ko.com/v1/iot/things/{{ states('sensor.alko_thingname') }}/state/desired

alko_bearer: >
  {{ state_attr('var.alko_access_token', 'token_type') }} {{ state_attr('var.alko_access_token', 'access_token') }}
```

What I don't know:

The "alko_access_token" and "token_type" is this something that needs to be replaced/entered manually? If so, where do I find this? (Currently I only have client ID, secret, username and password)

And is the below something I need to add in YAML somewhere or is this just an explanation?

> 
> Variables:
> 
>     act: boolean (avtive)
>     mar: boolean (margin)
>     pas: boolean (passage)
>     hour: number
>     minute: number
>     duration: number
>     ep: number
> 
> Possible entry points:
> 32: Base station
> 33: Random
> 0 bis 5: defined entry points
> 34:

**Comment by afuerhoff** [comment]
You have to authenticate at the api

/homeassistant/secrets.yaml: 
alko_payload_token: "**client_id**=xxx&**client_secret**=yyy&grant_type=**password**&**username**=zzz&password=www&scope=alkoCustomerId%20alkoCulture%20offline_access%20introspection"
alko_payload_refresh: "client_id=xxx&client_secret=yyy&grant_type=refresh_token&refresh_token={{ state_attr('var.alko_access_token', 'refresh_token') }}&scope=alkoCustomerId%20alkoCulture%20offline_access%20introspection"

/homeassistant/alko_robolinho_1423w.yaml:
var:
  alko_access_token:
    friendly_name: "Alko Access Token"
    unique_id: alko_access_token
    initial_value: 0
    restore: true
    attributes:
      expires_in: 0
      token_type: "unknown"
      refresh_token: "unknown"
      access_token: "unknown"

rest_command:
  #Get initial access token
  alko_get_initial_access_token:
    url: https://idp.al-ko.com/connect/token
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: !secret alko_payload_token
    verify_ssl: true

  #Token refresh
  alko_refresh_access_token:
    url: https://idp.al-ko.com/connect/token
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: !secret alko_payload_refresh
    verify_ssl: true

  alko_manualmowing_set:
    url: !secret alko_url_state_desired
    method: PATCH
    headers:
      Authorization: !secret alko_bearer
      Accept: application/json
    verify_ssl: true
    payload: >
      {
        "manualMowing": {
          "activityMode": {{ act }},
          "marginMode": {{ mar }},
          "narrowPassageMode": {{ pas }},
          "startHour": {{ hour }},
          "startMinute": {{ minute }},
          "duration": {{ duration }},
          "entryPoint": {{ ep }}
        }
      }


Automation:
Here you can define the variables:
![Image](https://github.com/user-attachments/assets/8defe3eb-ebd8-4b41-85ff-8853fc30355b)

**Comment by DIYtechie** [comment]
let me know if this is correct:

Added this to secrets.yaml:

```
alko_payload_token: >-
  client_id=xxx&
  client_secret=yyy&
  grant_type=password&
  username=zzz&
  password=www&
  scope=alkoCustomerId%20alkoCulture%20offline_access%20introspection

alko_payload_refresh: >-
  client_id=xxx&
  client_secret=yyy&
  grant_type=refresh_token&
  refresh_token={{ state_attr('var.alko_access_token', 'refresh_token') }}&
  scope=alkoCustomerId%20alkoCulture%20offline_access%20introspection

alko_url_state_desired: >-
  https://api.al-ko.com/v1/iot/things/{{ states('sensor.alko_thingname') }}/state/desired

alko_bearer: >-
  {{ state_attr('var.alko_access_token', 'token_type') }} {{ state_attr('var.alko_access_token', 'access_token') }}

```

(using my own credentials of course)

then added this to /homeassistant/packages/alko_token_management.yaml:

```
var:
  alko_access_token:
    friendly_name: "Alko Access Token"
    unique_id: alko_access_token
    initial_value: 0
    restore: true
    attributes:
      expires_in: 0
      token_type: "unknown"
      refresh_token: "unknown"
      access_token: "unknown"

rest_command:
  # Get initial access token
  alko_get_initial_access_token:
    url: https://idp.al-ko.com/connect/token
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: !secret alko_payload_token
    verify_ssl: true

  # Refresh access token
  alko_refresh_access_token:
    url: https://idp.al-ko.com/connect/token
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: !secret alko_payload_refresh
    verify_ssl: true

  # Set manual mowing parameters
  alko_manualmowing_set:
    url: !secret alko_url_state_desired
    method: PATCH
    headers:
      Authorization: "Bearer {{ state_attr('var.alko_access_token', 'access_token') }}"
      Accept: application/json
    verify_ssl: true
    payload: >
      {{ {
        "manualMowing": {
          "activityMode": act,
          "marginMode": mar,
          "narrowPassageMode": pas,
          "startHour": hour,
          "startMinute": minute,
          "duration": duration,
          "entryPoint": ep
        }
      } | to_json }}

sensor:
  - platform: rest
    name: Alko Token Response
    unique_id: alko_token_response
    resource: https://idp.al-ko.com/connect/token
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: !secret alko_payload_token
    scan_interval: 86400
    value_template: "{{ now().timestamp() | int }}"
    json_attributes:
      - access_token
      - refresh_token
      - expires_in
      - token_type

script:
  # Script to extract and store tokens from REST response (updated for var only)
  alko_store_tokens:
    alias: Store AL-KO tokens in vars
    sequence:
      - variables:
          response: >
            {{ state_attr('var.alko_access_token', 'response') if state_attr('var.alko_access_token', 'response') else namespace(data={}) }}

      - service: var.set
        data:
          entity_id: var.alko_access_token
        data_template:
          attributes:
            access_token: "{{ state_attr('sensor.alko_token_response', 'access_token') or 'unknown' }}"
            refresh_token: "{{ state_attr('sensor.alko_token_response', 'refresh_token') or 'unknown' }}"
            expires_in: "{{ state_attr('sensor.alko_token_response', 'expires_in') or 0 }}"
            token_type: "{{ state_attr('sensor.alko_token_response', 'token_type') or 'unknown' }}"

  # Script to manually trigger token retrieval and store result
  alko_get_token_manual:
    alias: Manually retrieve initial AL-KO token
    sequence:
      - service: rest_command.alko_get_initial_access_token
      - delay: "00:00:03"
      - service: script.alko_store_tokens

  # Script to manually refresh token and store result
  alko_refresh_token_manual:
    alias: Manually refresh AL-KO token
    sequence:
      - service: rest_command.alko_refresh_access_token
      - delay: "00:00:03"
      - service: script.alko_store_tokens

  # Script to trigger manual mowing session
  alko_start_manual_mowing:
    alias: Start manual mowing with AL-KO
    sequence:
      - service: rest_command.alko_manualmowing_set
        data:
          act: true
          mar: false
          pas: false
          hour: "{{ (now().timestamp() + 60) | timestamp_custom('%H', true) }}"
          minute: "{{ (now().timestamp() + 60) | timestamp_custom('%M', true) }}"
          duration: 30
          ep: 1

automation:
  # Automatically refresh the token every hour
  - alias: Automatically refresh AL-KO token hourly
    id: alko_refresh_token_hourly
    trigger:
      - platform: time_pattern
        minutes: "/59"
    action:
      - service: script.alko_refresh_token_manual
```

then implemented into configuration.yaml:

```
homeassistant:
  packages: !include_dir_named packages
```

Then restarted Home Assistant. The scripts for getting the token and refresh token seems to work and are stored in the variable.

However, when I try this in the developer tools:

```
action: rest_command.alko_manualmowing_set
data:
  act: true
  mar: false
  pas: false
  hour: 3
  minute: 25
  duration: 30
  ep: 1
```

I get error "403 Forbidden" as shown here:

<img width="560" alt="Image" src="https://github.com/user-attachments/assets/fbc626ab-6ef2-47d5-966a-c01930b2989f" />

Any idea how to make it work?

**Comment by afuerhoff** [comment]
You need also this sensor:


![Image](https://github.com/user-attachments/assets/51a4989e-f7d9-43d3-8af2-98a5b38277c0)

In this way you can implement a lot of sensors!

rest:
    resource: https://api.al-ko.com/v1/iot/things?pimInfo=false&thingState=true&accesses=false&thingCategory=ALKO-ROBOLINHO
    scan_interval: 31536000 # I use a refresh automation
    verify_ssl: true
    method: GET
    headers:
      Authorization: "{{ state_attr('var.alko_access_token', 'token_type') }} {{ state_attr('var.alko_access_token', 'access_token') }}"
      Accept: "application/json"
    sensor:
      - name: "Alko_thingName"
        unique_id: "Alko_thingName"
        value_template: >
          {% if value_json is defined and value_json is iterable and value_json | count > 0 and value_json[0] is mapping and value_json[0].thingName is defined %}
            {{ value_json[0].thingName }}
          {% else %}
            Unknown
          {% endif %}
        json_attributes:
        - thingType

**Comment by afuerhoff** [comment]
@DIYtechie: Another hint! You can run into trubble with your Alko user and password in URLs (URL encoding).
E.g.: @ has to code into %40 -> user: name@test.de -> name%40test.de

**Comment by DIYtechie** [comment]
I am afraid this is beyond my capabilities (at least for now).

Really hope this will be implemented as a built-in feature (including a built in option to start "now"). 

Then I would be able to just let Home Assistant control the mowing without on-device schedules and I could get a button to mow my front lawn or back lawn on command if I notice an extra round is necessary.

**Comment by afuerhoff** [comment]
It's not so complecated. -> https://www.w3schools.com/tags/ref_urlencode.ASP
Only special character are a problem.

**Comment by DIYtechie** [comment]
Awesome! Can't wait to try it out!

**Comment by DIYtechie** [comment]
Not sure what I am doing wrong, but I unfortunately can't seem to get this to work?

<img width="1223" alt="Image" src="https://github.com/user-attachments/assets/920bdadf-610b-4dd9-9598-d7fc09245f21" />

![Image](https://github.com/user-attachments/assets/d1f75355-c9c5-4e1b-9a0d-44c693f5bff9)

**Comment by jonkristian** [comment]
Is entrypoint 1 correct?, can you try with it emptied? Anything in the logs?

**Comment by jonkristian** [comment]
Hm,looks like it's missing an argument in the call, I will investigate tomorrow.

**Comment by afuerhoff** [comment]
I try it only in the actions dialog.

**Comment by jonkristian** [comment]
Hopefully [v0.3.5](https://github.com/jonkristian/alko/releases/tag/v0.3.5) fixes things. If you encounter any issues, please create a new ticket for each.

**Comment by afuerhoff** [comment]
Manual mowing is working

**Comment by DIYtechie** [comment]
Ahh, they are just +1 because the entrypoints start at 0. It works!

I use this script to get it to start immediately:

```
alias: Start front garden mowing now
sequence:
  - data:
      type: mow
      duration: 30
      entry_point: 2
      start_hour: "{{ now().hour }}"
      start_minute: "{{ now().minute }}"
    target:
      entity_id: lawn_mower.robolinho500_mower
    action: alko.start_manual_mowing
mode: single
description: ""

```
